project: puorl
env_name: hopper
eval_env_name: Hopper-v3
seed: 0
n_seeds: 2
algorithm: td3bc
method: sharing_all
max_steps: 1000000
eval_episodes: 10
log_interval: 10
vectorized: True

data:
  shift: body_mass
  positive_data_quality: medium_expert
  negative_data_quality: medium_expert
  input_type: sas
  labeled_ratio: 0.05
  positive_ratio: 0.7
  size: 1000000
  train_ratio: 0.8


td3bc:
  batch_size: 256
  n_jitted_updates: 8
  critic_lr: 1e-3
  actor_lr: 1e-3
  policy_freq: 2
  alpha: 2.5
  policy_noise_std: 0.2
  policy_noise_clip: 0.5
  tau: 0.005
  discount: 0.99

